<?php declare(strict_types = 1);

namespace Contributte\Neonizer\Encoder;

interface IEncoder
{

	public const GENERATED_MESSAGE = 'This file is auto-generated by neonizer';

	/**
	 * @param mixed[] $value
	 * @return string|NULL
	 */
	public function encode(array $value): ?string;

}
